version: "3.7"

x-datasource-variables: &datasource-variables
  DB_URL: jdbc:postgresql://adopet-db:5432/adopet-db
  DB_USERNAME: user
  DB_PASSWORD: 1234
x-postgres-variables: &postgres-variables
  POSTGRES_DB: adopet-db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: 1234

services:
  db:
    image: postgres
    container_name: adopet-db
    ports:
      - "54321:5432"
    environment:
      <<: *postgres-variables
    volumes:
      - adopet-db-volume:/var/lib/postgresql/data

  app:
    image: edsonmendes/adopet-api:latest
    container_name: adopet-app
    depends_on:
      - db
    ports:
      - "8888:8080"
    environment:
      <<: *datasource-variables

volumes:
  adopet-db-volume: